### ISSUE TITLE
CRAFT_ENVIRONMENT vs. ENVIRONMENT

### ISSUE THREAD

**Issue by swey** [craftcms/craft#8]
The `.env` uses `ENVIRONMENT`, while the CMS uses `CRAFT_ENVIRONMENT`. If the example env file is used, the environment variable will have no effect. Not sure, which one is the right.

https://github.com/craftcms/craft/blob/master/.env.example#L2
https://github.com/craftcms/cms/blob/develop/bootstrap/bootstrap.php#L104

**Comment by brandonkelly** [comment]
They both are right :)

All of Craft’s [PHP constants](https://github.com/craftcms/docs/blob/master/en/configuration.md#php-constants) begin with `CRAFT_` because their names aren’t configurable and something more generic (e.g. `ENVIRONMENT`) might conflict with other systems. So we err on the safe side for those.

The environment variables _are_ configurable though. This starter project just defines the default names, but you could change them if you wanted; it’s just a matter of updating your `.env` file and the `getenv()` calls in the various config files where they are accessed. Or in `ENVIRONMENT`’s case, in [web/index.php](https://github.com/craftcms/craft/blob/master/web/index.php#L19) and the [`craft` executable](https://github.com/craftcms/craft/blob/master/craft#L20).

**Comment by swey** [comment]
Ok, got it. Thank you!

Our problem was that we updated the env variables without updating the `web/index.php`
