### ISSUE TITLE
Security key variable removed from config/general.php

### ISSUE THREAD

**Issue by robzor** [craftcms/craft#85]
### Description
Hi there,

In this commit:
https://github.com/craftcms/craft/commit/34e84a1edb6af4fd1ec59bce45060f5e1f6e807c

You have removed the var:
`'securityKey' => App::env('CRAFT_SECURITY_KEY'),`

And I can't find any documentation to explain why this change has been made. I understand that you've renamed all the .env vars that are created to have a CRAFT_ prefix, but where is the security key now referenced? Is it just an assumed global type thing?

Servd (the hosting company) currently inject a `SECURITY_KEY` variable into a dynamic .env file, so I've let them know it should have a `CRAFT_` prefix, as I was getting this deprecation warning on their servers:

> "The auto-generated validation key stored at /var/www/html/storage/runtime/validation.key has been deprecated. Copy its value to the securityKey config setting in config/general.php."

### Additional info

- Craft version: 4.0.4
- PHP version: 8.0.17

**Comment by jamesmacwhite** [comment]
The reason is because of this here:

https://craftcms.com/docs/4.x/config/#config-environment-variables

> Craft’s [general config settings](https://craftcms.com/docs/4.x/config/config-settings.html) and [database connection settings](https://craftcms.com/docs/4.x/config/db-settings.html) can be defined exclusively by environment variables using a CRAFT_ or CRAFT_DB_ prefix respectively.

> Combine the prefix with the config setting in [screaming snake case(opens new window)](https://dev.to/fission/screaming-snake-case-43kj). The [allowUpdates](https://craftcms.com/docs/4.x/config/config-settings.html#allowupdates) setting, for example, would be CRAFT_ALLOW_UPDATES. The database [port](https://craftcms.com/docs/4.x/config/db-settings.html#port) setting would be CRAFT_DB_PORT.

In Craft CMS 4, any general config key can be overridden by an environment following the naming convention described. You no longer have to define it in the general config file itself, if you declare the environment variable matching the name format.

So the removal of the security key, is down to the fact Craft will look for CRAFT_SECURITY_KEY or any environment variable matching the convention i.e. CRAFT_ALLOW_UPDATES, without having to set it in general config. You can of course still set it to something else, but it just allows less work now.

**Comment by robzor** [comment]
Hi @jamesmacwhite thanks for getting back to me and providing the context for the change, much appreciated!
